In [1]:
import numpy as np


In [3]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [5]:
x=np.array([1,2,3,4,5])
print(x)
print('total elements=>',x.size)
print('dimension wise elements=>', x.shape)
print('dimension count', x.ndim)

[1 2 3 4 5]
total elements=> 5
dimension wise elements=> (5,)
dimension count 1


In [6]:
y=np.array([[2,3,5],[3,2,1]])
print(y)
print('total elements=>',y.size)
print('dimension wise elements=>', y.shape)
print('dimension count', y.ndim)

[[2 3 5]
 [3 2 1]]
total elements=> 6
dimension wise elements=> (2, 3)
dimension count 2


In [7]:
z=np.array([[2,3,5],[3,2,1],[5,6,9]])
print(z)
print('total elements=>',z.size)
print('dimension wise elements=>', z.shape)
print('dimension count', z.ndim)

[[2 3 5]
 [3 2 1]
 [5 6 9]]
total elements=> 9
dimension wise elements=> (3, 3)
dimension count 2


In [8]:
x=[1,2,3,4,5]
z=np.array([[x,x,x],[x,x,x],[x,x,x]])
print('shape',z.shape)
print(z)

shape (3, 3, 5)
[[[1 2 3 4 5]
  [1 2 3 4 5]
  [1 2 3 4 5]]

 [[1 2 3 4 5]
  [1 2 3 4 5]
  [1 2 3 4 5]]

 [[1 2 3 4 5]
  [1 2 3 4 5]
  [1 2 3 4 5]]]


In [10]:
x=[1,2,3,4,5,6,7,8,9,10]
z=np.array([x,x,x,x,x,x,x,x,x,x])
print(z)
print('total elements=>',z.size)
print('dimension wise elements=>', z.shape)
print('dimension count', z.ndim)

[[ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]]
total elements=> 100
dimension wise elements=> (10, 10)
dimension count 2


In [11]:
np.arange(0,10,0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [14]:
d=np.arange(-10,11,0.5)
d.shape


(42,)

In [15]:
d.reshape(6,7)


array([[-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ],
       [ -6.5,  -6. ,  -5.5,  -5. ,  -4.5,  -4. ,  -3.5],
       [ -3. ,  -2.5,  -2. ,  -1.5,  -1. ,  -0.5,   0. ],
       [  0.5,   1. ,   1.5,   2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5,   6. ,   6.5,   7. ],
       [  7.5,   8. ,   8.5,   9. ,   9.5,  10. ,  10.5]])

In [16]:
d.reshape(2,3,7)

array([[[-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ],
        [ -6.5,  -6. ,  -5.5,  -5. ,  -4.5,  -4. ,  -3.5],
        [ -3. ,  -2.5,  -2. ,  -1.5,  -1. ,  -0.5,   0. ]],

       [[  0.5,   1. ,   1.5,   2. ,   2.5,   3. ,   3.5],
        [  4. ,   4.5,   5. ,   5.5,   6. ,   6.5,   7. ],
        [  7.5,   8. ,   8.5,   9. ,   9.5,  10. ,  10.5]]])

In [19]:
a=np.linspace(1,1000,11)
a

array([   1. ,  100.9,  200.8,  300.7,  400.6,  500.5,  600.4,  700.3,
        800.2,  900.1, 1000. ])

In [21]:
d=np.random.randint(1,6,(10,10))
print(d)

[[3 3 2 5 1 2 1 5 3 1]
 [4 1 5 5 4 1 2 4 2 4]
 [2 5 1 3 5 5 3 3 1 3]
 [1 2 5 1 5 4 3 4 5 5]
 [5 3 5 2 2 4 4 4 1 4]
 [4 3 1 2 1 4 1 1 2 4]
 [1 5 5 2 2 2 5 5 2 1]
 [3 3 4 3 5 5 4 1 5 2]
 [5 2 3 4 3 2 2 1 1 3]
 [5 2 3 2 5 3 2 1 3 3]]


In [22]:
d[0]

array([3, 3, 2, 5, 1, 2, 1, 5, 3, 1])

In [23]:
d[-1]


array([5, 2, 3, 2, 5, 3, 2, 1, 3, 3])

In [24]:
d[0,0]

3

In [25]:
d[0][0]

3

In [26]:
d[:,0]#all row of coloum index 0

array([3, 4, 2, 1, 5, 4, 1, 3, 5, 5])

In [27]:
d[:,-3]


array([5, 4, 3, 4, 4, 1, 5, 1, 1, 1])

In [28]:
d[:5,2]#first five rows of coloumn indx 2

array([2, 5, 1, 5, 5])

In [ ]:
d[-1,5:]